### PR TITLE
Workspaces are back!

### PR DESCRIPTION
**Pull request by esimkowitz**

### CODE REVIEW

**Comment by chottuthejimmy** [comment]
@esimkowitz the test failed for this PR, there's a blank gray screen when the application is opened. 
This was the downloaded [artifact](https://api.github.com/repos/wavetermdev/waveterm/actions/artifacts/2228461600/zip)

Check it out and lmk if its an issue with the PR itself or something from our end.

**Comment by esimkowitz** [comment]
Requested access to view the result

**Comment by chottuthejimmy** [comment]
Wdym access ?
You don't have the access to view the recordings ? Like any of the test results ?

Super sorry for that. 
Just curious, who has got access to the rec from your org ?
Basically there will be a dashcam account for your org through which the api is added to the repos secrets.
I am not sure tho, if ian just added the api from his side without creating a dashcam account for you guys. 

If you do have the dashcam account, just ask the admin to add you over there and you will have access to all the rec

Once again sorry for the inconvenience mate 😔 we will have it fixed by the night!

**Comment by ianjennings** [comment]
Hey @esimkowitz,

I've updated the last replay from CI to be available, and all future replays within your account as "unlisted."

Can you please check your email for an invite to the Dashcam team? It may be a few months old.

Ian

**Comment by esimkowitz** [comment]
@chottuthejimmy @ianjennings found the issue, should be fixed now

**Comment by esimkowitz** [comment]
Also @ianjennings found the email and joined the team, thanks for the heads-up!

**Comment by chottuthejimmy** [comment]
> @chottuthejimmy @ianjennings found the issue, should be fixed now

I think this would be our first automated test which actually caught a bug! 🎉

**Pull request merged**
