### PR TITLE
remove unused cmd

### PR DESCRIPTION
**Pull request by chottuthejimmy**

### CODE REVIEW

**Comment by esimkowitz** [comment]
Looks like my change worked, but now the results aren't getting commented into the PR

**Comment by chottuthejimmy** [comment]
Ohh ya.

**Comment by chottuthejimmy** [comment]
@esimkowitz its a bug at our end, we are on it.

**Comment by ianjennings** [comment]
@esimkowitz To clairfy? Do you want results posted as comments within the PR? Or the "green checkmark" within the "github checks"

**Comment by esimkowitz** [comment]
I think ideally both, is that possible?

**Pull request merged**
