### PR TITLE
Add Golang SAST and SCA checks

### PR DESCRIPTION
**Pull request by kamushadenes**
This PR adds security checks for the Golang components

### CODE REVIEW

**Comment by esimkowitz** [comment]
What's the advantage of these CI tools vs. the CodeQL setup we already have? Also curious if you've taken a look at this repo? https://github.com/securego/gosec

**Comment by kamushadenes** [comment]
golangci-lint is a lint of linters (one of them being gosec). 

It checks for many different things, not only security related, but also performance etc. Checks more stuff than CodeQL.

govulncheck is SCA like Dependabot, but also works with the runtime itself.

They can both be integrated with GitHub security alerts.

**Comment by kamushadenes** [comment]
Let's try to merge https://github.com/wavetermdev/waveterm/pull/734 first or else golangci-lint will complain a lot.

**Comment by esimkowitz** [comment]
@kamushadenes sorry I tried to change the base branch for this to our new main branch and it automatically closed the PR. Can you reopen this PR targeting our new main branch?

**Pull request closed without merging**
